# Generated by Django 3.0 on 2022-03-21 14:27

import django.core.validators
from django.db import migrations, models
import geoposition.fields
import reviews.models.photo_restaurant
import reviews.models.photo_review
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoRestaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='date when the object was created', verbose_name='creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='date when the object was modified', verbose_name='update date')),
                ('photo_one', models.ImageField(blank=True, null=True, upload_to=reviews.models.photo_restaurant.create_path_photo_restaurant, verbose_name='Photo One')),
                ('order', models.IntegerField(verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Photo Restaurant',
                'verbose_name_plural': 'Photos Restaurants',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='date when the object was created', verbose_name='creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='date when the object was modified', verbose_name='update date')),
                ('photo_one', models.ImageField(blank=True, null=True, upload_to=reviews.models.photo_review.create_path_photo_review, verbose_name='Photo One')),
                ('order', models.IntegerField(verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Photo Review',
                'verbose_name_plural': 'Photos Reviews',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='date when the object was created', verbose_name='creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='date when the object was modified', verbose_name='update date')),
                ('name', models.CharField(max_length=555, verbose_name='Name')),
                ('nit', models.CharField(max_length=20, verbose_name='NIT')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('location', geoposition.fields.GeopositionField(blank=True, max_length=42, null=True, verbose_name='Location')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Web Site')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('score', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Score')),
                ('date_create', models.DateField(verbose_name='Date Create')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='date when the object was created', verbose_name='creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='date when the object was modified', verbose_name='update date')),
                ('title', models.CharField(max_length=555, verbose_name='Title')),
                ('date', models.DateField(verbose_name='date')),
                ('description', models.TextField(verbose_name='Description')),
                ('score_service', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=5, verbose_name='Score Service')),
                ('score_food', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=5, verbose_name='Score Food')),
                ('score_environment', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=5, verbose_name='Score Environment')),
                ('score_quality_price', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=5, verbose_name='Score Quality Price')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopRestaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='date when the object was created', verbose_name='creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='date when the object was modified', verbose_name='update date')),
                ('top', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number Top')),
                ('score', models.IntegerField(blank=True, default=0, null=True, verbose_name='Score')),
            ],
            options={
                'verbose_name': 'Top Restaurant',
                'verbose_name_plural': 'Top Restaurants',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
