# Generated by Django 3.0 on 2022-03-21 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toprestaurant',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='user who created the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toprestaurant_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creation user'),
        ),
        migrations.AddField(
            model_name='toprestaurant',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='user who performed the update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toprestaurant_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='update user'),
        ),
        migrations.AddField(
            model_name='toprestaurant',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.Restaurant', verbose_name='Restaurant'),
        ),
        migrations.AddField(
            model_name='review',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='user who created the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creation user'),
        ),
        migrations.AddField(
            model_name='review',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='user who performed the update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='update user'),
        ),
        migrations.AddField(
            model_name='review',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='person'),
        ),
        migrations.AddField(
            model_name='review',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Restaurant', verbose_name='restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='user who created the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creation user'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='user who performed the update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='update user'),
        ),
        migrations.AddField(
            model_name='photoreview',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='user who created the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photoreview_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creation user'),
        ),
        migrations.AddField(
            model_name='photoreview',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='user who performed the update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photoreview_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='update user'),
        ),
        migrations.AddField(
            model_name='photoreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Review', verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='photorestaurant',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='user who created the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photorestaurant_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creation user'),
        ),
        migrations.AddField(
            model_name='photorestaurant',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='user who performed the update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photorestaurant_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='update user'),
        ),
        migrations.AddField(
            model_name='photorestaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Restaurant', verbose_name='Restaurant'),
        ),
    ]
