# Generated by Django 3.0 on 2022-03-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220226_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
