# Generated by Django 3.0 on 2022-03-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220321_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.TextField(blank=True, null=True, verbose_name='Category'),
        ),
    ]
