# Generated by Django 3.0 on 2022-03-22 16:26

from django.db import migrations, models
import reviews.models.review


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_restaurant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='score_environment',
            field=models.CharField(default='0', max_length=5, verbose_name='Score Environment'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='score_food',
            field=models.CharField(default='0', max_length=5, verbose_name='Score Food'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='score_quality_price',
            field=models.CharField(default='0', max_length=5, verbose_name='Score Quality Price'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='score_service',
            field=models.CharField(default='0', max_length=5, verbose_name='Score Service'),
        ),
        migrations.AddField(
            model_name='review',
            name='photo_one',
            field=models.ImageField(blank=True, null=True, upload_to=reviews.models.review.create_path_photo_review, verbose_name='Photo One'),
        ),
        migrations.AddField(
            model_name='review',
            name='photo_three',
            field=models.ImageField(blank=True, null=True, upload_to=reviews.models.review.create_path_photo_review, verbose_name='Photo Three'),
        ),
        migrations.AddField(
            model_name='review',
            name='photo_two',
            field=models.ImageField(blank=True, null=True, upload_to=reviews.models.review.create_path_photo_review, verbose_name='Photo Two'),
        ),
    ]
