# Generated by Django 3.0 on 2022-03-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_restaurant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='top',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number Top'),
        ),
    ]
