# Generated by Django 3.0 on 2022-03-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220322_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='score_environment',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Score Environment'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='score_food',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Score Food'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='score_quality_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Score Quality Price'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='score_service',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Score Service'),
        ),
    ]
