# Generated by Django 3.0 on 2022-03-13 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0004_restaurant_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='top',
        ),
        migrations.CreateModel(
            name='TopRestaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='date when the object was created', verbose_name='creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='date when the object was modified', verbose_name='update date')),
                ('top', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number Top')),
                ('created_by', models.ForeignKey(blank=True, help_text='user who created the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toprestaurant_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creation user')),
                ('modified_by', models.ForeignKey(blank=True, help_text='user who performed the update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toprestaurant_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='update user')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.Restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Top Restaurant',
                'verbose_name_plural': 'Top Restaurants',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
