# Generated by Django 3.0 on 2022-03-13 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220313_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='toprestaurant',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number Top'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='score',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Score'),
        ),
    ]
