# Generated by Django 3.0 on 2022-03-23 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220322_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='count_reviews',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Count Reviews'),
        ),
    ]
