# Generated by Django 3.0 on 2022-03-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_restaurant_count_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score_environment',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=6, verbose_name='Score Environment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_food',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=6, verbose_name='Score Food'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_quality_price',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=6, verbose_name='Score Quality Price'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_service',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=6, verbose_name='Score Service'),
        ),
    ]
