# Generated by Django 3.0 on 2022-03-23 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20220322_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='count_reviews',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count Reviews'),
        ),
    ]
