# Generated by Django 3.0 on 2022-02-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfigurationm',
            name='page_facebook_url',
        ),
        migrations.AlterField(
            model_name='siteconfigurationm',
            name='page_twitter_url',
            field=models.CharField(blank=True, default='#', max_length=255, null=True, verbose_name='Page of Facebook'),
        ),
    ]
