# Generated by Django 3.0 on 2022-03-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_auto_20220227_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfigurationm',
            name='page_twitter_url',
            field=models.CharField(blank=True, default='#', max_length=255, null=True, verbose_name='Page of Twitter'),
        ),
    ]
