# Generated by Django 3.0 on 2022-03-24 01:44

import commons.models.site_configuration
from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_auto_20220310_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfigurationm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=commons.models.site_configuration.create_path_category, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='siteconfigurationm',
            name='location',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True, verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='siteconfigurationm',
            name='page_instagram_url',
            field=models.CharField(blank=True, default='#', max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='siteconfigurationm',
            name='page_twitter_url',
            field=models.CharField(blank=True, default='#', max_length=255, null=True, verbose_name='Twitter'),
        ),
    ]
