# Generated by Django 3.0 on 2022-02-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='rol',
            field=models.CharField(blank=True, help_text='Reviewer = RW, Restaurant = RT, Admin = AD', max_length=10, null=True, verbose_name='Rol'),
        ),
    ]
